pull_request_title: "Translations: Update Translations"
commit_message: "chore(Translations): :globe_with_meridians: Update %language% translations in %original_file_name%"
append_commit_message: false
pull_request_labels:
  - translation
  - l10n
files:
  - source: /docs/en/
    translation: /docs/%two_letters_code%/%original_file_name%
  - source: /lib/i18n/languages/en.json
    translation: /lib/i18n/languages/%two_letters_code%.json
